---

rules:
  lodash-fp/consistent-compose: 'off'
  lodash-fp/consistent-name:
  - error
  - _
  lodash-fp/no-argumentless-calls: error
  lodash-fp/no-chain: error
  lodash-fp/no-extraneous-args: error
  lodash-fp/no-extraneous-function-wrapping: error
  lodash-fp/no-extraneous-iteratee-args: error
  lodash-fp/no-for-each: error
  lodash-fp/no-partial-of-curried: error
  lodash-fp/no-single-composition: error
  lodash-fp/no-submodule-destructuring: error
  lodash-fp/no-unused-result: error
  lodash-fp/prefer-compact: error
  lodash-fp/prefer-composition-grouping: error
  lodash-fp/prefer-constant:
  - error
  - arrowFunctions: false
  lodash-fp/prefer-flat-map: error
  lodash-fp/prefer-get: error
  lodash-fp/prefer-identity:
  - error
  - arrowFunctions: false
  lodash-fp/preferred-alias: error
  lodash-fp/use-fp: error
  fp/no-arguments: error
  fp/no-class: off
  fp/no-delete: error
  fp/no-events: error
  fp/no-get-set: error
  fp/no-let: error
  fp/no-loops: error
  fp/no-mutating-assign: error
  fp/no-mutating-methods: error
  fp/no-mutation:
  - error
  - "allowThis": true
  fp/no-nil: off
  fp/no-proxy: error
  fp/no-rest-parameters: error
  fp/no-this: off
  fp/no-throw: off
  fp/no-unused-expression: error
  fp/no-valueof-field: error
  no-var: error

plugins:
  - fp
  - "lodash-fp"
